[project]
name = "playwright-cucumber-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "allure-behave>=2.14.2",
    "behave>=1.2.6",
    "playwright>=1.52.0",
]
